#!/usr/bin/env bash
eval nix-store -qR --include-outputs $(nix-store -qd $(nix-build -A decorated-cospans.components)) | grep '\.drv$' | cachix push o1lo01ol1o
eval nix-store -qR --include-outputs $(nix-store -qd $(nix-build -A decorated-cospans.components)) | cachix push o1lo01ol1o
eval nix-store -qR --include-outputs $(nix-store -qd $(nix-build shell-hoogle.nix)) | grep '\.drv$' | cachix push o1lo01ol1o
eval nix-store -qR --include-outputs $(nix-store -qd $(nix-build shell-hoogle.nix)) | cachix push o1lo01ol1o

